server:
  port: 8080
#  servlet:
#    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cosmetic_web"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: cnweb
    password: cnweb
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

outbound:
  identity:
    client-id: "<client-id>"
    client-secret: "<client-secret>"
    redirect-uri: "http://localhost:8080/frontend/html/authenticate.html"

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

cloudinary:
  cloud-name: dhhr73s2r
  api-key: 897441952787276
  api-secret: 8jdFz8R---oPj00URWVD0oStd3E